#spring:
#  jpa:
#    open-in-view: false
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/dh}
#    username: ${POSTGRES_USERNAME:postgres}
#    password: ${POSTGRES_PASSWORD:hieu112004}
#    driver-class-name: org.postgresql.Driver
spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/task-flow}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver


jwt:
  access-token:
    secret-key: b3NpbnRfYXBpX2F1dGhvcml6YXRpb25AMjAyM19hY2Nlc3NfdG9rZW5=ed
    ttl: 2592000000
  refresh-token:
    secret-key: b3NpbnRfYXBpX2F1dGhvcml6YXRpb25AMjAyM19yZWZyZXNoX3Rva2Vuew
    ttl: 2592000000